language: python
python:
    - "2.7"
branches:
  only:
    - master
    - /^v[0-9].*$/
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/anaconda/bin:$PATH
    # Update conda
    - conda update --yes conda
    # Add in Fortran compiler and R
    - sudo apt-get install -y gfortran r-base
install:
    # Create conda matching requirements
    - conda create --yes -n venv python=$TRAVIS_PYTHON_VERSION -f environment.yaml
    - source activate venv
    # Rest of dependencies
    - "pip install -r requirements-dev.txt"
    - "pip install pytest"
    # Install YATSM
    - "pip install -e ."
script:
    - py.test tests/
    - coverage run --source yatsm -m py.test
after_success:
    - pip install coveralls
    - coverage report
    - coveralls
